eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10087/eureka/
server:
  port: 9899
spring:
  application:
    name: eurekaclient
  rabbitmq:
    host:localhost
    port: 5672
    username: guest
  sleuth:
    sampler:
      percentage: 1.0
